ARG PLAYWRIGHT_VERSION
ARG PLAYWRIGHT_NPM_VERSION
FROM mcr.microsoft.com/playwright:${PLAYWRIGHT_VERSION} AS builder

WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM mcr.microsoft.com/playwright:${PLAYWRIGHT_VERSION}
ARG PLAYWRIGHT_NPM_VERSION

WORKDIR /app
COPY package*.json ./
RUN node -e \
      "const fs = require('fs'); const manifest = require('./package.json'); delete manifest.devDependencies; manifest.dependencies['@playwright/test'] = '${PLAYWRIGHT_NPM_VERSION}'; manifest.dependencies.playwright = '${PLAYWRIGHT_NPM_VERSION}'; fs.writeFileSync('package.json', JSON.stringify(manifest));" && \
    npm install --omit=dev --package-lock=false
COPY --from=builder /app/dist ./dist

ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
ENV PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1

CMD ["node", "dist/index.js"]
