name: "Questions / Help 💬"
description: If you have questions, please check the docs or Discord
title: "[Please read the message below]"
labels: [":speech_balloon: Question"]
body:
  - type: markdown
    attributes:
      value: |
        ## Questions and Help

        This issue tracker is reserved for bug reports, documentation requests, and feature requests.

        For anything else, such as questions or getting help, please see:

        - [The Playrunner documentation](https://playrunner.github.io/playrunner/docs/)
        - [Our Discord server](https://discord.gg/23yz25kat)
  - type: checkboxes
    id: no-post
    attributes:
      label: |
        Please do not submit this issue.
      description: |
        > [!IMPORTANT]
        > This issue will be closed.
      options:
        - label: I understand that this issue will be closed
          required: true
