export const ORCHESTRATOR_BOOTSTRAP_ENV = "PLAYRUNNER_ORCHESTRATOR_BOOTSTRAP";
export const ORCHESTRATOR_BOOTSTRAP_HEADER =
  "x-playrunner-orchestrator-bootstrap";
export const ORCHESTRATOR_BOOTSTRAP_MAX_BYTES = 4 * 1024;
export const ORCHESTRATOR_PAYLOAD_MAX_BYTES = 10 * 1024 * 1024;
